name: Build ReasonReact App (Melange + Vite)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04  # 24.04はdarcsが無いため要注意

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # - name: Set up OCaml
      #   uses: ocaml/setup-ocaml@v2
      #   with:
      #     ocaml-compiler: 5.1.1
      #     opam-disable-sandboxing: true

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y opam
          opam init

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm + opam dependencies
        run: |
          npm run init
          npm run check-npm-deps

      - name: Build project
        run: |
          eval $(opam env)
          npm run build

      - name: Deploy build to gh-pages
        run: |
          git config user.name "ryoryoryo3838"
          git config user.email "miya.klis.default@gmail.com"
          git checkout --orphan gh-pages
          git --work-tree=dist add --all
          git --work-tree=dist commit -m "Deploy"
          git push origin HEAD:gh-pages --force